version: '3.8'
services:
 dynamodb-local:
  command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
  image: "amazon/dynamodb-local:latest"
  container_name: dynamodb-local
  ports:
    - "8000:8000"
  volumes:
    - "./docker/dynamodb:/home/dynamodblocal/data"
  working_dir: /home/dynamodblocal
  healthcheck:
    test: ["CMD-SHELL", "exit 1"]
    interval: 5s
    timeout: 5s
    retries: 5

 rabbitmq:
  image: rabbitmq:latest
  container_name: rabbitmq
  ports:
  - "5672:5672"
  - "15672:15672"
  environment:
    RABBITMQ_DEFAULT_USER: guest
    RABBITMQ_DEFAULT_PASS: guest
  healthcheck:
    test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
    interval: 10s
    retries: 5
    start_period: 30s
    timeout: 10s
  
 spring-application:
  container_name: clean-architecture
  build:
    context: .
    dockerfile: deployment/Dockerfile
  ports:
    - 8080:8080
  environment:
    AWS_ENDPOINT: http://docker-desktop:8000
    RABBITMQ_HOST: docker-desktop
    AWS_PROFILE_ACTIVE: no-credentials
  tty: true
  depends_on:
    rabbitmq:
      required: true
      condition: service_healthy