server:
  port: 8080
spring:
  application:
    name: "NameProject"
  # devtools:
  #   add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
    active: ${AWS_PROFILE_ACTIVE}
  rabbitmq:
    host: ${RABBITMQ_HOST} 
  

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
  
aws:
  dynamodb:
    endpoint: ${AWS_ENDPOINT}
  region: "us-east-1"
